// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function CreateItem(arg1) {
  return window['go']['main']['App']['CreateItem'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListItems(arg1, arg2) {
  return window['go']['main']['App']['ListItems'](arg1, arg2);
}

export function RecordLaunch(arg1) {
  return window['go']['main']['App']['RecordLaunch'](arg1);
}

export function ScanShortcuts() {
  return window['go']['main']['App']['ScanShortcuts']();
}

export function UpdateGroup(arg1) {
  return window['go']['main']['App']['UpdateGroup'](arg1);
}

export function UpdateItem(arg1) {
  return window['go']['main']['App']['UpdateItem'](arg1);
}
