// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ApplyHotkeys(arg1:Array<domain.HotkeyBinding>):Promise<domain.HotkeyApplyResult>;

export function ClearItems():Promise<number>;

export function CreateGroup(arg1:domain.GroupInput):Promise<domain.Group>;

export function CreateItem(arg1:domain.ItemInput):Promise<domain.Item>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteItem(arg1:string):Promise<void>;

export function GetCursorAnchorPosition(arg1:number,arg2:number):Promise<domain.Point>;

export function LaunchItem(arg1:string):Promise<domain.Item>;

export function ListGroups():Promise<Array<domain.Group>>;

export function ListItems(arg1:string,arg2:string):Promise<Array<domain.Item>>;

export function ListScanRoots():Promise<Array<string>>;

export function OpenItemLocation(arg1:string):Promise<void>;

export function PickIconSource():Promise<string>;

export function PickScanRoot():Promise<string>;

export function PickTargetFolder():Promise<string>;

export function PickTargetPath():Promise<string>;

export function PreviewIconFromSource(arg1:string):Promise<string>;

export function RecordLaunch(arg1:string):Promise<domain.Item>;

export function RefreshItemIcon(arg1:string):Promise<domain.Item>;

export function ScanShortcuts(arg1:Array<string>):Promise<domain.ScanResult>;

export function SetFavorite(arg1:string,arg2:boolean):Promise<domain.Item>;

export function SyncIcons():Promise<number>;

export function UpdateGroup(arg1:domain.Group):Promise<domain.Group>;

export function UpdateItem(arg1:domain.ItemUpdate):Promise<domain.Item>;

export function UpdateItemIconFromSource(arg1:string,arg2:string):Promise<domain.Item>;
