// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyHotkeys(arg1) {
  return window['go']['main']['App']['ApplyHotkeys'](arg1);
}

export function ClearItems() {
  return window['go']['main']['App']['ClearItems']();
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function CreateItem(arg1) {
  return window['go']['main']['App']['CreateItem'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function GetCursorAnchorPosition(arg1, arg2) {
  return window['go']['main']['App']['GetCursorAnchorPosition'](arg1, arg2);
}

export function ImportGroupRules(arg1) {
  return window['go']['main']['App']['ImportGroupRules'](arg1);
}

export function LaunchItem(arg1) {
  return window['go']['main']['App']['LaunchItem'](arg1);
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListItems(arg1, arg2) {
  return window['go']['main']['App']['ListItems'](arg1, arg2);
}

export function ListScanRoots() {
  return window['go']['main']['App']['ListScanRoots']();
}

export function OpenItemLocation(arg1) {
  return window['go']['main']['App']['OpenItemLocation'](arg1);
}

export function PickIconSource() {
  return window['go']['main']['App']['PickIconSource']();
}

export function PickRuleFile() {
  return window['go']['main']['App']['PickRuleFile']();
}

export function PickScanRoot() {
  return window['go']['main']['App']['PickScanRoot']();
}

export function PickTargetFolder() {
  return window['go']['main']['App']['PickTargetFolder']();
}

export function PickTargetPath() {
  return window['go']['main']['App']['PickTargetPath']();
}

export function PreviewIconFromSource(arg1) {
  return window['go']['main']['App']['PreviewIconFromSource'](arg1);
}

export function RecordLaunch(arg1) {
  return window['go']['main']['App']['RecordLaunch'](arg1);
}

export function RefreshItemIcon(arg1) {
  return window['go']['main']['App']['RefreshItemIcon'](arg1);
}

export function ScanShortcuts(arg1) {
  return window['go']['main']['App']['ScanShortcuts'](arg1);
}

export function SetFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetFavorite'](arg1, arg2);
}

export function SyncIcons() {
  return window['go']['main']['App']['SyncIcons']();
}

export function UpdateGroup(arg1) {
  return window['go']['main']['App']['UpdateGroup'](arg1);
}

export function UpdateItem(arg1) {
  return window['go']['main']['App']['UpdateItem'](arg1);
}

export function UpdateItemIconFromSource(arg1, arg2) {
  return window['go']['main']['App']['UpdateItemIconFromSource'](arg1, arg2);
}
