// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateGroup(arg1:domain.GroupInput):Promise<domain.Group>;

export function CreateItem(arg1:domain.ItemInput):Promise<domain.Item>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteItem(arg1:string):Promise<void>;

export function LaunchItem(arg1:string):Promise<domain.Item>;

export function ListGroups():Promise<Array<domain.Group>>;

export function ListItems(arg1:string,arg2:string):Promise<Array<domain.Item>>;

export function OpenItemLocation(arg1:string):Promise<void>;

export function RecordLaunch(arg1:string):Promise<domain.Item>;

export function RefreshItemIcon(arg1:string):Promise<domain.Item>;

export function ScanShortcuts():Promise<domain.ScanResult>;

export function SetFavorite(arg1:string,arg2:boolean):Promise<domain.Item>;

export function SyncIcons():Promise<number>;

export function UpdateGroup(arg1:domain.Group):Promise<domain.Group>;

export function UpdateItem(arg1:domain.ItemUpdate):Promise<domain.Item>;
